apiVersion: v2
name: jenkins
description: A Helm chart for deploying Jenkins with Argo CD
type: application
version: 0.1.0
dependencies:
  - name: jenkins
    version: 13.6.10
    repository: https://charts.bitnami.com/bitnami

